name: Daily YouTube Email
on:
  repository_dispatch:
    types: [cron-trigger]
  workflow_dispatch:
    inputs:
      dispatch_id:
        description: An ID used to identify the workflow run
        required: true
        type: string
      wait_time:
        description: Time to wait before echoing
        required: true
        type: string
      message:
        description: Message to echo after waiting
        required: true
        type: string

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Run script
        run: go run main.go
        env:
          API_KEY: ${{ secrets.API_KEY }}
          BASE_URL: ${{secrets.BASE_URL}}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
          EMAIL_SENDER_NAME: ${{ secrets.EMAIL_SENDER_NAME }}
          # Add other secrets as needed

      - name: Commit last email timestamp
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add logs.txt
          git diff --quiet && git diff --staged --quiet || git commit -m "Update last email timestamp"
          git push

  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch ${{ inputs.dispatch_id }}
        run: echo "Dispatch ${{ inputs.dispatch_id }}"
  wait-and-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Wait
        run: sleep ${{ inputs.wait_time }}
      - name: Echo
        run: echo "${{ inputs.message }}"
