name: Daily YouTube Email
on:
  schedule:
    - cron: "30 * * * *"
  workflow_dispatch: # Allows manual trigger for testing

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Run script
        run: go run main.go
        env:
          API_KEY: ${{ secrets.API_KEY }}
          BASE_URL: ${{secrets.BASE_URL}}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
          EMAIL_SENDER_NAME: ${{ secrets.EMAIL_SENDER_NAME }}
          # Add other secrets as needed
